DROP TABLE IF EXISTS REGIAO CASCADE;
DROP TABLE IF EXISTS CONTA CASCADE;
DROP TABLE IF EXISTS PERFIL CASCADE;
DROP TABLE IF EXISTS GENERO CASCADE;
DROP TABLE IF EXISTS PERFIL_PREFERE CASCADE;
DROP TABLE IF EXISTS DIRETOR CASCADE;
DROP TABLE IF EXISTS ATOR CASCADE;
DROP TABLE IF EXISTS CONTEUDO CASCADE;
DROP TABLE IF EXISTS AUDIO CASCADE;
DROP TABLE IF EXISTS LEGENDA CASCADE;
DROP TABLE IF EXISTS AUDIO_LEGENDA CASCADE;
DROP TABLE IF EXISTS TEMPORADAS CASCADE;
DROP TABLE IF EXISTS EPISODIOS CASCADE;
DROP TABLE IF EXISTS LEGENDA_AUDIO_EPISODIOS CASCADE;
DROP TABLE IF EXISTS LEGENDA_AUDIO_FILMES CASCADE;
DROP TABLE IF EXISTS LISTA_PERFIL CASCADE;
DROP TABLE IF EXISTS MOTIVO_RECOMENDACAO CASCADE;
DROP TABLE IF EXISTS RECOMENDACOES_PERFIL CASCADE;
DROP TABLE IF EXISTS DISPONIVEL_PARA CASCADE;
DROP TABLE IF EXISTS ESTRELANDO CASCADE;
DROP TABLE IF EXISTS DO_GENERO CASCADE;
DROP TABLE IF EXISTS DIRIGIDO_POR CASCADE;
DROP TABLE IF EXISTS ASSISTIR CASCADE;

CREATE TABLE REGIAO
	(nome VARCHAR(200) NOT NULL,
PRIMARY KEY(nome));
 
CREATE TABLE  CONTA
	(id VARCHAR(30) NOT NULL UNIQUE,
	email VARCHAR(254) NOT NULL UNIQUE,
	plano VARCHAR(10) NOT NULL,
	telasonline NUMERIC(1) NOT NULL,
	cpf NUMERIC(11) NOT NULL UNIQUE,
	cartao_titular VARCHAR(26) NOT NULL,
	cartao_numero NUMERIC(19) NOT NULL,
	cartao_cvv NUMERIC(4) NOT NULL,
	cartao_val DATE NOT NULL,
	senha VARCHAR(64) NOT NULL,
PRIMARY KEY (id));

CREATE TABLE PERFIL
	(id VARCHAR NOT NULL UNIQUE,
	id_conta VARCHAR(30) NOT NULL,
	nome VARCHAR(50) NOT NULL,
	imagem VARCHAR(255) NOT NULL, --endereco do arquivo de imagem
	regiao VARCHAR(20),
PRIMARY KEY(id_conta, id),
FOREIGN KEY(id_conta) REFERENCES CONTA(id) 
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY(regiao) REFERENCES REGIAO(nome) 
ON DELETE SET NULL);

CREATE TABLE GENERO
	(id  VARCHAR(7)
	nome VARCHAR(30) UNIQUE,
PRIMARY KEY(nome));

CREATE TABLE PERFIL_PREFERE --preferencia do usuario por generos
	(id_conta VARCHAR(30) NOT NULL,	
	id_perfil VARCHAR NOT NULL,
	id_genero VARCHAR(30) NOT NULL,
	ordem NUMERIC(3) NOT NULL,
PRIMARY KEY(id_conta, id_perfil, id_genero),
FOREIGN KEY(id_conta, id_perfil) REFERENCES PERFIL(id_conta, id) 
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY(id_genero) REFERENCES GENERO(id) 
ON DELETE CASCADE
ON UPDATE CASCADE);
 
CREATE TABLE CINEASTA
	(id VARCHAR(30)
	nome VARCHAR(150) NOT NULL,
PRIMARY KEY (id));

CREATE TABLE CONTEUDO
	(id VARCHAR(30) NOT NULL,
	nome VARCHAR(150) NOT NULL,
	ano NUMERIC(4) NOT NULL,
	sinopse VARCHAR(400) NOT NULL,
	poster VARCHAR(255) NOT NULL UNIQUE,
	ci NUMERIC(2) NOT NULL,
	original BOOLEAN NOT NULL,
	tipo VARCHAR(5) NOT NULL,--tipicamente 'serie', 'filme' ou 'episodio'
CONSTRAINT chck_type CHECK(tipo IN('serie', 'filme', 'episodio')),
PRIMARY KEY (id));

CREATE TABLE ASSISTIVEL
	(id_conteudo VARCHAR(30) NOT NULL,
	tipo_conteudo VARCHAR(
	arquivo	VARCHAR(255) NOT NULL UNIQUE,
	visualizacoes INT,
PRIMARY KEY(id_conteudo),
FOREIGN KEY(id_conteudo) REFERENCES CONTEUDO(id));

CREATE TABLE EPISODIO
	(id_assistivel VARCHAR(30) NOT NULL,
	temporada NUMERIC(3) NOT NULL,
	numero NUMERIC(3) NOT NULL,
PRIMARY KEY(id_assistivel),
FOREIGN KEY(id_assistivel) REFERENCES ASSISTIVEL(id_conteudo) 
FOREIGN KEY(temporada) REFERENCES TEMPORADAS(numero) 
ON DELETE CASCADE);

CREATE TABLE LEGENDA_AUDIO --tabela que contem as opcoes de audio e legenda para os assistiveis
	(id_conteudo VARCHAR(30) NOT NULL,
	nome_arquivo VARCHAR(255) NOT NULL UNIQUE,
PRIMARY KEY(id_conteudo, nome_arquivo),
FOREIGN KEY(id_conteudo) REFERENCES CONTEUDO(id) 
ON DELETE CASCADE);

CREATE TABLE TEMPORADAS
	(id_serie VARCHAR(30) NOT NULL,
	numero NUMERIC(2) NOT NULL,
PRIMARY KEY(id_serie, numero),
FOREIGN KEY(id_serie) REFERENCES CONTEUDO(id) 
ON DELETE CASCADE);

CREATE TABLE LISTA_PERFIL --lista de conteudos ("para ver depois") de um perfil
	(id_conta VARCHAR(30) NOT NULL,
	perfil VARCHAR(50) NOT NULL,
	id_conteudo VARCHAR(30) NOT NULL,
PRIMARY KEY(id_conta, perfil, id_conteudo),
FOREIGN KEY(id_conta, perfil) REFERENCES PERFIL(id_conta, nome) 
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY(id_conteudo) REFERENCES CONTEUDO(id) 
ON DELETE CASCADE);

CREATE TABLE MOTIVO_RECOMENDACAO --tabela de motivos pre-especificados pelos quais um conteudo pode ser recomendado a um usuario
	(motivo VARCHAR(50) NOT NULL,
PRIMARY KEY(motivo));

CREATE TABLE RECOMENDACOES_PERFIL --tabela de conteudos recomendados especificamente para um perfil
	(email_perfil VARCHAR(254) NOT NULL,
	nome_perfil VARCHAR(50) NOT NULL,
	id_conteudo VARCHAR(30) NOT NULL,
	motivo VARCHAR(30) NOT NULL,
PRIMARY KEY(email_perfil, nome_perfil, id_conteudo),
FOREIGN KEY(email_perfil, nome_perfil) REFERENCES PERFIL(email_conta, nome) 
ON DELETE CASCADE,
FOREIGN KEY(motivo) REFERENCES MOTIVO_RECOMENDACAO(motivo) 
ON DELETE CASCADE
ON UPDATE CASCADE);
	
CREATE TABLE DISPONIVEL_PARA --disponibilidade de obra em regioes
	(conteudo_id VARCHAR(30) NOT NULL,
	regiao_nome VARCHAR(200) NOT NULL,
PRIMARY KEY(conteudo_id, regiao_nome),
FOREIGN KEY(conteudo_id) REFERENCES CONTEUDO(id) 
ON DELETE CASCADE,
FOREIGN KEY(regiao_nome) REFERENCES REGIAO(nome) 
ON DELETE CASCADE);

CREATE TABLE ESTRELANDO --atores presentes em obra
	(conteudo_id VARCHAR(30) NOT NULL,
	ator_nome VARCHAR(150) NOT NULL,
PRIMARY KEY(conteudo_id, ator_nome),
FOREIGN KEY(conteudo_id) REFERENCES CONTEUDO(id) 
ON DELETE CASCADE,
FOREIGN KEY(ator_nome) REFERENCES ATOR(nome) 
ON DELETE CASCADE
ON UPDATE CASCADE);

CREATE TABLE DO_GENERO --generos da obra
	(conteudo_id VARCHAR(30) NOT NULL,
	genero_nome VARCHAR(30) NOT NULL,
PRIMARY KEY(conteudo_id, genero_nome),
FOREIGN KEY(conteudo_id) REFERENCES CONTEUDO(id) 
ON DELETE CASCADE,
FOREIGN KEY (genero_nome) REFERENCES GENERO(nome) 
ON DELETE CASCADE
ON UPDATE CASCADE);

CREATE TABLE DIRIGIDO_POR --diretores da obra
	(conteudo_id VARCHAR(30) NOT NULL,
	nome_diretor VARCHAR(150) NOT NULL,
PRIMARY KEY(conteudo_id, nome_diretor),
FOREIGN KEY(conteudo_id) REFERENCES CONTEUDO(id) 
ON DELETE CASCADE,
FOREIGN KEY(nome_diretor) REFERENCES DIRETOR(nome) 
ON DELETE CASCADE
ON UPDATE CASCADE);
	
CREATE TABLE ASSISTIR 
	(email_conta VARCHAR(254) NOT NULL,
	perfil	VARCHAR(50) NOT NULL,
	conteudo_id VARCHAR(30) NOT NULL,
	assitido_comp BOOLEAN NOT NULL,
	feedback CHAR(8), --tipicamente assume os valores "positivo" ou "negativo"
	ultimo_ep_visto CHAR(6),
	no_tempo NUMERIC(4),
	relevancia NUMERIC(100),
CONSTRAINT chck_feedback CHECK( feedback IN ('positivo', 'negativo')),
PRIMARY KEY(email_conta, perfil, conteudo_id),
FOREIGN KEY(email_conta, perfil) REFERENCES PERFIL(email_conta, nome) 
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY(conteudo_id) REFERENCES CONTEUDO(id) 
ON DELETE CASCADE);
